export type SantoView = 'attract' | 'home' | 'names' | 'mine' | 'general' | 'menu';

export type SantoEvent = {
  dayId: string;
  start: string;
  end: string;
  title: string;
  place: string;
};

export type Santo = {
  id: string;
  name: string;
  events: SantoEvent[];
};

export const SANTO_META = {
  short: 'Pujya Santo',
  title: 'NAAM 2026',
  datesLabel: 'October 8 – 11, 2026',
  itineraryLabel: 'Santo itinerary · Oct 5 – 15',
} as const;

export const DAYS = [
  { id: 'mon5', short: 'Mon', label: 'Monday', date: 'Oct 5', iso: '2026-10-05', kicker: 'Arrival' },
  { id: 'tue6', short: 'Tue', label: 'Tuesday', date: 'Oct 6', iso: '2026-10-06', kicker: 'Pravrutti' },
  { id: 'wed7', short: 'Wed', label: 'Wednesday', date: 'Oct 7', iso: '2026-10-07', kicker: 'Briefing' },
  { id: 'thu8', short: 'Thu', label: 'Thursday', date: 'Oct 8', iso: '2026-10-08', kicker: 'Travel to Edison' },
  { id: 'fri9', short: 'Fri', label: 'Friday', date: 'Oct 9', iso: '2026-10-09', kicker: 'Keynotes 1 & 2' },
  { id: 'sat10', short: 'Sat', label: 'Saturday', date: 'Oct 10', iso: '2026-10-10', kicker: 'Keynotes 3 & 4' },
  { id: 'sun11', short: 'Sun', label: 'Sunday', date: 'Oct 11', iso: '2026-10-11', kicker: 'Akshardham · DC' },
  { id: 'mon12', short: 'Mon', label: 'Monday', date: 'Oct 12', iso: '2026-10-12', kicker: 'DC' },
  { id: 'tue13', short: 'Tue', label: 'Tuesday', date: 'Oct 13', iso: '2026-10-13', kicker: 'DC' },
  { id: 'wed14', short: 'Wed', label: 'Wednesday', date: 'Oct 14', iso: '2026-10-14', kicker: 'DC' },
  { id: 'thu15', short: 'Thu', label: 'Thursday', date: 'Oct 15', iso: '2026-10-15', kicker: 'Departure' },
] as const;

const e = (dayId: string, start: string, end: string, title: string, place: string): SantoEvent => ({
  dayId,
  start,
  end,
  title,
  place,
});

export const SANTOS: Santo[] = [
  {
    id: 'viraldarshan',
    name: 'Viraldarshan Swami',
    events: [
      e('thu8', '5:00 PM', '7:00 PM', 'Mukhpath Testing', 'BK Wing'),
      e('thu8', '7:30 PM', '9:00 PM', 'Mukhpath Testing', 'BK Wing'),
      e('fri9', '11:00 AM', '12:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('fri9', '12:30 PM', '2:00 PM', 'Mukhpath Testing', 'BK Wing'),
      e('fri9', '3:00 PM', '4:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('sat10', '11:00 AM', '12:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('sat10', '12:30 PM', '2:00 PM', 'Mukhpath Testing', 'BK Wing'),
    ],
  },
  {
    id: 'aniketmuni',
    name: 'Aniketmuni Swami',
    events: [
      e('thu8', '5:00 PM', '7:00 PM', 'Mukhpath Testing', 'BK Wing'),
      e('thu8', '7:30 PM', '9:00 PM', 'Mukhpath Testing', 'BK Wing'),
      e('fri9', '11:00 AM', '12:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('fri9', '12:30 PM', '2:00 PM', 'Mukhpath Testing', 'BK Wing'),
      e('fri9', '3:00 PM', '4:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('sat10', '11:00 AM', '12:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('sat10', '12:30 PM', '2:00 PM', 'Mukhpath Testing', 'BK Wing'),
    ],
  },
  {
    id: 'achalniket',
    name: 'Achalniket Swami',
    events: [
      e('thu8', '5:00 PM', '7:00 PM', 'Mukhpath Testing', 'BK Wing'),
      e('thu8', '7:30 PM', '9:00 PM', 'Mukhpath Testing', 'BK Wing'),
      e('fri9', '11:00 AM', '12:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('fri9', '12:30 PM', '2:00 PM', 'Mukhpath Testing', 'BK Wing'),
      e('fri9', '3:00 PM', '4:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('sat10', '11:00 AM', '12:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('sat10', '12:30 PM', '2:00 PM', 'Mukhpath Testing', 'BK Wing'),
      e('sat10', '8:00 PM', '8:30 PM', 'Dessert Serving', 'Banquet Hall'),
    ],
  },
  {
    id: 'achalnayan',
    name: 'Achalnayan Swami',
    events: [
      e('thu8', '5:00 PM', '7:00 PM', 'Mukhpath Testing', 'BK Wing'),
      e('thu8', '7:00 PM', '7:30 PM', 'Evening Mandir Aarti', 'Nij Mandir'),
      e('thu8', '7:30 PM', '9:00 PM', 'Mukhpath Testing', 'BK Wing'),
      e('fri9', '11:00 AM', '12:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('fri9', '12:30 PM', '2:00 PM', 'Mukhpath Testing', 'BK Wing'),
      e('fri9', '3:00 PM', '4:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('fri9', '8:00 PM', '8:30 PM', 'Dessert Serving', 'Banquet Hall'),
      e('sat10', '11:00 AM', '12:30 PM', 'PCs Breakout', 'Yogi Hall'),
      e('sat10', '12:30 PM', '2:00 PM', 'Mukhpath Testing', 'BK Wing'),
    ],
  },
  {
    id: 'vatsalmurti',
    name: 'Vatsalmurti Swami',
    events: [
      e('thu8', '5:00 PM', '7:00 PM', 'Mukhpath Testing', 'BK Wing'),
      e('thu8', '7:30 PM', '9:00 PM', 'Mukhpath Testing', 'BK Wing'),
      e('fri9', '11:00 AM', '12:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('fri9', '12:30 PM', '2:00 PM', 'Mukhpath Testing', 'BK Wing'),
      e('fri9', '3:00 PM', '4:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('sat10', '11:00 AM', '12:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('sat10', '12:30 PM', '2:00 PM', 'Mukhpath Testing', 'BK Wing'),
      e('sun11', '7:00 AM', '7:30 AM', 'Morning Mandir Aarti', 'Nij Mandir'),
    ],
  },
  {
    id: 'akhandanand',
    name: 'Akhandanand Swami',
    events: [
      e('thu8', '5:00 PM', '7:00 PM', 'Mukhpath Testing', 'BK Wing'),
      e('thu8', '7:30 PM', '9:00 PM', 'Mukhpath Testing', 'BK Wing'),
      e('fri9', '11:00 AM', '12:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('fri9', '12:30 PM', '2:00 PM', 'Mukhpath Testing', 'BK Wing'),
      e('fri9', '3:00 PM', '4:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('sat10', '11:00 AM', '12:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('sat10', '12:30 PM', '2:00 PM', 'Mukhpath Testing', 'BK Wing'),
      e('sat10', '7:00 PM', '7:30 PM', 'Evening Mandir Aarti', 'Nij Mandir'),
    ],
  },
  {
    id: 'narayansankalp',
    name: 'Narayansankalp Swami',
    events: [
      e('thu8', '7:00 PM', '7:30 PM', 'Evening Mandir Aarti', 'Nij Mandir'),
      e('fri9', '11:00 AM', '12:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('fri9', '3:00 PM', '4:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('fri9', '8:00 PM', '8:30 PM', 'Dessert Serving', 'Banquet Hall'),
      e('sat10', '11:00 AM', '12:30 PM', 'Santo Breakout', 'Yogi Hall'),
    ],
  },
  {
    id: 'paramniket',
    name: 'Paramniket Swami',
    events: [
      e('thu8', '8:00 PM', '8:30 PM', 'Dessert Serving', 'Banquet Hall'),
      e('fri9', '11:00 AM', '12:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('fri9', '3:00 PM', '4:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('sat10', '11:00 AM', '12:30 PM', 'Santo Breakout', 'Yogi Hall'),
    ],
  },
  {
    id: 'narayantirth',
    name: 'Narayantirth Swami',
    events: [
      e('thu8', '8:00 PM', '8:30 PM', 'Dessert Serving', 'Banquet Hall'),
      e('fri9', '11:00 AM', '12:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('fri9', '3:00 PM', '4:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('sat10', '11:00 AM', '11:30 AM', 'PC Track Breakout', 'Yogi Hall'),
      e('sat10', '11:00 AM', '12:30 PM', 'Santo Breakout', 'Yogi Hall'),
    ],
  },
  {
    id: 'saralyogi',
    name: 'Saralyogi Swami',
    events: [
      e('fri9', '11:00 AM', '12:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('fri9', '3:00 PM', '4:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('fri9', '7:00 PM', '7:30 PM', 'Evening Mandir Aarti', 'Nij Mandir'),
      e('sat10', '11:00 AM', '12:30 PM', 'Santo Breakout', 'Yogi Hall'),
    ],
  },
  {
    id: 'yoganand',
    name: 'Yoganand Swami',
    events: [
      e('fri9', '9:15 AM', '10:15 AM', 'Katha (9:37–10:17)', 'Sahajanand Hall'),
      e('fri9', '11:00 AM', '12:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('fri9', '3:00 PM', '4:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('sat10', '11:00 AM', '12:30 PM', 'Santo Breakout', 'Yogi Hall'),
    ],
  },
  {
    id: 'sarangkirtan',
    name: 'Sarangkirtan Swami',
    events: [
      e('fri9', '11:00 AM', '12:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('fri9', '3:00 PM', '4:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('fri9', '6:45 PM', '7:15 PM', 'Sabha Hall Aarti', 'Sahajanand Hall'),
      e('sat10', '11:00 AM', '12:30 PM', 'Santo Breakout', 'Yogi Hall'),
    ],
  },
  {
    id: 'nityavivek',
    name: 'Nityavivek Swami',
    events: [
      e('fri9', '11:00 AM', '12:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('fri9', '3:00 PM', '4:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('sat10', '7:00 AM', '7:30 AM', 'Morning Mandir Aarti', 'Nij Mandir'),
      e('sat10', '11:00 AM', '12:30 PM', 'Santo Breakout', 'Yogi Hall'),
    ],
  },
  {
    id: 'uttamshlok',
    name: 'Uttamshlok Swami',
    events: [
      e('fri9', '11:00 AM', '12:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('fri9', '3:00 PM', '4:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('sat10', '7:00 AM', '7:30 AM', 'Morning Mandir Aarti', 'Nij Mandir'),
      e('sat10', '11:00 AM', '12:30 PM', 'Santo Breakout', 'Yogi Hall'),
    ],
  },
  {
    id: 'anantmangal',
    name: 'Anantmangal Swami',
    events: [
      e('fri9', '11:00 AM', '12:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('fri9', '3:00 PM', '4:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('sat10', '9:15 AM', '10:45 AM', 'Keynote Program 3', 'Sahajanand Hall'),
      e('sat10', '11:00 AM', '12:30 PM', 'Santo Breakout', 'Yogi Hall'),
    ],
  },
  {
    id: 'brahmatilak',
    name: 'Brahmatilak Swami',
    events: [
      e('fri9', '11:00 AM', '12:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('fri9', '3:00 PM', '4:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('sat10', '11:00 AM', '12:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('sat10', '7:00 PM', '7:30 PM', 'Evening Mandir Aarti', 'Nij Mandir'),
    ],
  },
  {
    id: 'shantipriya',
    name: 'Shantipriya Swami',
    events: [
      e('fri9', '11:00 AM', '12:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('fri9', '3:00 PM', '4:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('sat10', '11:00 AM', '11:30 AM', 'PC Track Breakout', 'Yogi Hall'),
      e('sat10', '11:00 AM', '12:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('sat10', '8:00 PM', '8:30 PM', 'Dessert Serving', 'Banquet Hall'),
    ],
  },
  {
    id: 'nirdoshswarup',
    name: 'Nirdoshswarup Swami',
    events: [
      e('fri9', '11:00 AM', '12:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('fri9', '3:00 PM', '4:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('sat10', '11:00 AM', '12:30 PM', 'Santo Breakout', 'Yogi Hall'),
      e('sun11', '7:00 AM', '7:30 AM', 'Morning Mandir Aarti', 'Nij Mandir'),
    ],
  },
].sort((a, b) => a.name.localeCompare(b.name));

export const GENERAL: Record<string, SantoEvent[]> = {
  mon5: [e('mon5', '6:00 AM', '9:00 PM', 'Arrival all day', 'Campus')],
  tue6: [
    e('tue6', '7:00 AM', '7:30 AM', 'Arti', 'Mandir'),
    e('tue6', '7:30 AM', '8:30 AM', 'Breakfast', 'Dining'),
    e('tue6', '8:30 AM', '9:30 AM', 'Katha', 'Hall'),
    e('tue6', '9:30 AM', '12:00 PM', 'Satsang Pravrutti Library', 'Campus'),
    e('tue6', '12:00 PM', '1:00 PM', 'Lunch', 'Dining'),
    e('tue6', '1:00 PM', '4:00 PM', 'Rest', 'Utaro'),
    e('tue6', '4:00 PM', '4:30 PM', 'Refreshments', 'Campus'),
    e('tue6', '4:30 PM', '7:00 PM', 'Satsang AI · IT · NC27', 'Hall'),
    e('tue6', '7:00 PM', '7:30 PM', 'Arti', 'Mandir'),
    e('tue6', '7:30 PM', '8:30 PM', 'Dinner', 'Dining'),
    e('tue6', '8:30 PM', '9:00 PM', 'Chesta', 'Hall'),
  ],
  wed7: [
    e('wed7', '7:00 AM', '7:30 AM', 'Arti', 'Mandir'),
    e('wed7', '7:30 AM', '8:30 AM', 'Breakfast', 'Dining'),
    e('wed7', '8:30 AM', '9:15 AM', 'Katha', 'Hall'),
    e('wed7', '9:15 AM', '10:00 AM', 'Travel to Staff Briefing Room', 'Campus'),
    e('wed7', '10:00 AM', '11:00 AM', 'AI Awareness · common session', 'Hall'),
    e('wed7', '11:00 AM', '12:00 PM', 'CA · common session', 'Hall'),
    e('wed7', '12:00 PM', '1:00 PM', 'Lunch', 'Dining'),
    e('wed7', '1:00 PM', '4:00 PM', 'Rest', 'Utaro'),
    e('wed7', '4:00 PM', '4:30 PM', 'Refreshments', 'Campus'),
    e('wed7', '4:30 PM', '5:00 PM', 'Calendar 2027 · common session', 'Hall'),
    e('wed7', '5:00 PM', '6:00 PM', 'Santo Exhibition Tour', 'Campus'),
    e('wed7', '6:00 PM', '7:00 PM', 'FERA · common session', 'Hall'),
    e('wed7', '7:00 PM', '7:30 PM', 'Arti', 'Mandir'),
    e('wed7', '7:30 PM', '8:30 PM', 'Dinner', 'Dining'),
    e('wed7', '8:30 PM', '9:00 PM', 'Chesta', 'Hall'),
  ],
  thu8: [
    e('thu8', '7:00 AM', '7:30 AM', 'Arti', 'Mandir'),
    e('thu8', '7:30 AM', '8:30 AM', 'Breakfast', 'Dining'),
    e('thu8', '9:00 AM', '10:30 AM', 'Santo Exhibition Tour', 'Campus'),
    e('thu8', '10:30 AM', '12:00 PM', 'Akshardham Smruti Sabha', 'Akshardham'),
    e('thu8', '12:00 PM', '1:00 PM', 'Lunch', 'Dining'),
    e('thu8', '1:00 PM', '3:00 PM', 'Travel to Edison', 'Edison'),
    e('thu8', '3:00 PM', '5:00 PM', 'Rest at Utaro / Meet NAAM delegates', 'Utaro'),
    e('thu8', '5:00 PM', '7:00 PM', 'Arrival, check-in & mukhpath testing', 'Lobby · BK Wing'),
    e('thu8', '7:00 PM', '7:30 PM', 'Arti', 'Mandir'),
    e('thu8', '7:30 PM', '9:00 PM', 'Dinner & Dessert', 'Dining'),
    e('thu8', '9:00 PM', '9:30 PM', 'Depart to Utaro', 'Utaro'),
  ],
  fri9: [
    e('fri9', '6:30 AM', '7:00 AM', 'Travel to Mandir', 'Mandir'),
    e('fri9', '7:00 AM', '8:00 AM', 'Arti, Darshan, Abhishek', 'Mandir'),
    e('fri9', '8:00 AM', '9:00 AM', 'Breakfast', 'Dining'),
    e('fri9', '9:00 AM', '9:15 AM', 'Seating', 'Sahajanand Hall'),
    e('fri9', '9:15 AM', '10:45 AM', 'Keynote Program 1 · i/eBKY combined', 'Sahajanand Hall'),
    e('fri9', '10:45 AM', '11:00 AM', 'Travel', 'Campus'),
    e('fri9', '11:00 AM', '12:30 PM', 'Santo Breakout · BKY RC / RCTL / RA', 'Yogi Hall'),
    e('fri9', '12:30 PM', '2:00 PM', 'Lunch / Mukhpath Testing', 'Dining · BK Wing'),
    e('fri9', '2:00 PM', '2:45 PM', 'Goshthi 1', 'Hall'),
    e('fri9', '2:45 PM', '3:00 PM', 'Travel', 'Campus'),
    e('fri9', '3:00 PM', '4:30 PM', 'Santo Breakout · Campus & Education', 'Yogi Hall'),
    e('fri9', '4:30 PM', '5:00 PM', 'Group photo & snacks', 'Campus'),
    e('fri9', '5:00 PM', '5:15 PM', 'Seating', 'Sahajanand Hall'),
    e('fri9', '5:15 PM', '6:45 PM', 'Keynote Program 2 · i/eBKY combined', 'Sahajanand Hall'),
    e('fri9', '6:45 PM', '7:15 PM', 'Sabha Hall Aarti', 'Sahajanand Hall'),
    e('fri9', '7:30 PM', '9:00 PM', 'Dinner & Dessert', 'Dining'),
    e('fri9', '9:00 PM', '9:30 PM', 'Depart to Utaro', 'Utaro'),
  ],
  sat10: [
    e('sat10', '6:30 AM', '7:00 AM', 'Travel to Mandir', 'Mandir'),
    e('sat10', '7:00 AM', '8:00 AM', 'Arti, Darshan, Abhishek', 'Mandir'),
    e('sat10', '8:00 AM', '9:00 AM', 'Breakfast', 'Dining'),
    e('sat10', '9:00 AM', '9:15 AM', 'Seating', 'Sahajanand Hall'),
    e('sat10', '9:15 AM', '10:45 AM', 'Keynote Program 3 · i/eBKY combined', 'Sahajanand Hall'),
    e('sat10', '10:45 AM', '11:00 AM', 'Travel', 'Campus'),
    e('sat10', '11:00 AM', '12:30 PM', 'Santo Breakout · BST / KST', 'Yogi Hall'),
    e('sat10', '12:30 PM', '2:00 PM', 'Lunch / Mukhpath Testing', 'Dining · BK Wing'),
    e('sat10', '2:00 PM', '2:45 PM', 'Goshthi 2', 'Hall'),
    e('sat10', '2:45 PM', '3:00 PM', 'Travel', 'Campus'),
    e('sat10', '3:00 PM', '4:30 PM', 'Regional Review', 'Hall'),
    e('sat10', '4:30 PM', '5:00 PM', 'Snacks & Travel', 'Campus'),
    e('sat10', '5:00 PM', '5:15 PM', 'Seating', 'Sahajanand Hall'),
    e('sat10', '5:15 PM', '7:00 PM', 'Keynote Program 4 · i/eBKY combined', 'Sahajanand Hall'),
    e('sat10', '7:30 PM', '9:00 PM', 'Dinner & Dessert', 'Dining'),
    e('sat10', '9:00 PM', '9:30 PM', 'Depart to Utaro', 'Utaro'),
  ],
  sun11: [
    e('sun11', '7:00 AM', '7:30 AM', 'Arti, Darshan, Abhishek', 'Mandir'),
    e('sun11', '7:30 AM', '8:15 AM', 'Breakfast (Edison)', 'Dining'),
    e('sun11', '8:15 AM', '9:00 AM', 'Travel to Robbinsville', 'Akshardham'),
    e('sun11', '9:00 AM', '10:30 AM', 'Darshan / Breakfast · Robbinsville', 'Akshardham'),
    e('sun11', '10:30 AM', '12:00 PM', 'Museum Special Dedication Ceremony', 'Akshardham'),
    e('sun11', '12:00 PM', '1:00 PM', 'Lunch', 'Akshardham'),
    e('sun11', '1:00 PM', '4:00 PM', 'Travel to DC', 'Washington, DC'),
    e('sun11', '4:00 PM', '7:00 PM', 'DC Bhumi Pujan', 'DC'),
    e('sun11', '7:00 PM', '7:30 PM', 'Arti', 'DC'),
    e('sun11', '7:30 PM', '8:30 PM', 'Dinner', 'DC'),
    e('sun11', '8:30 PM', '9:00 PM', 'Chesta', 'DC'),
  ],
  mon12: [
    e('mon12', '7:00 AM', '8:00 AM', 'Arti, Darshan, Abhishek', 'Mandir'),
    e('mon12', '8:00 AM', '9:00 AM', 'Breakfast', 'Dining'),
    e('mon12', '9:00 AM', '10:00 AM', 'Sant Katha', 'Hall'),
    e('mon12', '10:00 AM', '11:00 AM', 'Corporate Affairs / Compliance', 'Hall'),
    e('mon12', '11:00 AM', '12:00 PM', 'Public Affairs', 'Hall'),
    e('mon12', '12:00 PM', '1:00 PM', 'Bhumi Pujan Session 2', 'DC'),
    e('mon12', '1:00 PM', '2:00 PM', 'Lunch', 'Dining'),
    e('mon12', '2:00 PM', '4:00 PM', 'Rest', 'Utaro'),
    e('mon12', '4:00 PM', '4:30 PM', 'Refreshments', 'Campus'),
    e('mon12', '4:30 PM', '5:30 PM', 'Data Governance', 'Hall'),
    e('mon12', '5:30 PM', '6:30 PM', 'Aksharpith', 'Hall'),
    e('mon12', '6:30 PM', '7:00 PM', 'Local Sabha', 'Hall'),
    e('mon12', '7:00 PM', '7:30 PM', 'Arti', 'Mandir'),
    e('mon12', '7:30 PM', '8:30 PM', 'Dinner', 'Dining'),
    e('mon12', '8:30 PM', '9:00 PM', 'Chesta', 'Hall'),
  ],
  tue13: [
    e('tue13', '7:00 AM', '8:00 AM', 'Arti, Darshan, Abhishek', 'Mandir'),
    e('tue13', '8:00 AM', '9:00 AM', 'Breakfast', 'Dining'),
    e('tue13', '9:00 AM', '10:00 AM', 'Break / Transit', 'Campus'),
    e('tue13', '11:00 AM', '12:00 PM', 'Sant Milan', 'Hall'),
    e('tue13', '12:00 PM', '1:00 PM', 'Lunch', 'Dining'),
    e('tue13', '1:00 PM', '3:00 PM', 'Rest', 'Utaro'),
    e('tue13', '4:00 PM', '5:00 PM', 'Travel to Mandir', 'Mandir'),
    e('tue13', '5:00 PM', '6:00 PM', 'Break / Clean up', 'Campus'),
    e('tue13', '6:00 PM', '7:00 PM', 'Local Sabha', 'Hall'),
    e('tue13', '7:00 PM', '7:30 PM', 'Arti', 'Mandir'),
    e('tue13', '7:30 PM', '8:30 PM', 'Dinner', 'Dining'),
    e('tue13', '8:30 PM', '9:00 PM', 'Chesta', 'Hall'),
  ],
  wed14: [
    e('wed14', '7:00 AM', '8:00 AM', 'Arti, Darshan, Abhishek', 'Mandir'),
    e('wed14', '8:00 AM', '9:00 AM', 'Breakfast', 'Dining'),
    e('wed14', '9:00 AM', '10:00 AM', 'Break / Transit', 'Campus'),
    e('wed14', '10:00 AM', '12:00 PM', 'Aksharpith', 'Hall'),
    e('wed14', '12:00 PM', '1:00 PM', 'Lunch', 'Dining'),
    e('wed14', '1:00 PM', '4:00 PM', 'Rest', 'Utaro'),
    e('wed14', '4:00 PM', '4:30 PM', 'Refreshments', 'Campus'),
    e('wed14', '4:30 PM', '5:15 PM', 'Communications', 'Hall'),
    e('wed14', '5:15 PM', '6:00 PM', 'Publications', 'Hall'),
    e('wed14', '6:00 PM', '7:00 PM', 'Sant Sabha', 'Hall'),
    e('wed14', '7:00 PM', '7:30 PM', 'Arti', 'Mandir'),
    e('wed14', '7:30 PM', '8:30 PM', 'Dinner', 'Dining'),
    e('wed14', '8:30 PM', '9:00 PM', 'Chesta', 'Hall'),
  ],
  thu15: [e('thu15', '6:00 AM', '9:00 PM', 'Departure all day', 'Campus')],
};

export type MenuSlot = 'breakfast' | 'lunch' | 'dinner' | 'sweets';

export const SANTO_MENU = [
  {
    id: 'thu8',
    short: 'Thu',
    label: 'Thursday',
    date: 'Oct 8',
    meals: [
      {
        slot: 'dinner' as const,
        name: 'Dinner',
        items: [
          'Mexican chili with jalapeño bread',
          'Ravioli',
          'Lettuce wraps',
          'Masala papad',
          'Mushroom palak shaak',
          'Saahi paneer',
          'Paratha / naan',
          'Grilled vegetables',
          'Jeera rice',
          'Dal makhani',
          'Cannoli',
        ],
      },
      {
        slot: 'sweets' as const,
        name: 'Sweets',
        items: ['Brownies and mini bundt cakes', 'Assorted baked goods (TBD)'],
      },
    ],
  },
  {
    id: 'fri9',
    short: 'Fri',
    label: 'Friday',
    date: 'Oct 9',
    meals: [
      {
        slot: 'breakfast' as const,
        name: 'Breakfast',
        items: ['Muthiya', 'Mug', 'Avocado toast', 'Scones', 'Donuts', 'Mamra', 'Fresh fruit juice bar'],
      },
      {
        slot: 'lunch' as const,
        name: 'Lunch',
        items: [
          'Orange philo cups',
          'Falafel bowl / wrap',
          'Vegan ball sandwiches',
          'Dahivada',
          'Dalvada',
          'Rotli',
          'Tindoda bataka',
          'Kobij bateta',
          'Chora',
          'Bhat',
          'Dal',
          'Mediterranean salad',
          'Papdi',
        ],
      },
      {
        slot: 'dinner' as const,
        name: 'Dinner',
        items: [
          'Pie and ice cream (flavor TBD)',
          'Coldstone ice cream',
          'Cupcakes',
          'Mexican boat',
          'Mexican stuffed shells',
          'Soy wraps',
          'Bhinda nu shaak',
          'Cauliflower bataka',
          'Bhakri / paratha',
          'Corn avocado salad',
          'Khichdi',
          'Kadhi',
        ],
      },
    ],
  },
  {
    id: 'sat10',
    short: 'Sat',
    label: 'Saturday',
    date: 'Oct 10',
    meals: [
      {
        slot: 'breakfast' as const,
        name: 'Breakfast',
        items: [
          'Cabbage pauva (TBD)',
          'Mug',
          'Bagels · plain & jalapeño cheddar',
          'Sticky cinnamon rolls',
          'Cake',
          'Dry tikhi puri',
          'Tres leche mini cake',
        ],
      },
      {
        slot: 'lunch' as const,
        name: 'Lunch',
        items: [
          'Vegan sliders',
          'Grilled halloumi arugula sandwich',
          'Mix veg pakoda',
          'Rotli',
          'Parvar',
          'Methi bataka / squash',
          'Kala chana',
          'Bhat',
          'Dal',
          'Watermelon salad',
          'Papad',
        ],
      },
      {
        slot: 'dinner' as const,
        name: 'Dinner',
        items: [
          'Dessert bar',
          'Pizza (Kaushalnidhi Swami)',
          'Sushi',
          'Artichoke dip and chips',
          'Undhiyu',
          'Sev tameta',
          'Bhakri',
          'Italian salad',
          'Khichdi',
          'Kadhi',
        ],
      },
      {
        slot: 'sweets' as const,
        name: 'Sweets',
        items: ['Coffee cake', 'Cookies'],
      },
    ],
  },
  {
    id: 'sun11',
    short: 'Sun',
    label: 'Sunday',
    date: 'Oct 11',
    meals: [
      {
        slot: 'breakfast' as const,
        name: 'Breakfast',
        items: ['Mug', 'Tofu scramble burrito', 'Muffins', 'Banana bread', 'Vagharela cereal'],
      },
      {
        slot: 'sweets' as const,
        name: 'Sweets',
        items: ['Muffins', 'Banana bread'],
      },
    ],
  },
] as const;
